v1 = 10.0
v2 = 1.0
v3 = 0.5
v4 = 0.5
v5 = 1.0
v6 = 0.5
v8 = 360.0
v7 = 0.0
t1 = gh("Construct Domain", v8, v7)  # component has no native Python form
v9 = 60.0
v10 = 0.0
t2 = gh("Construct Domain", v9, v10)  # component has no native Python form
t4 = gh("Point", )  # component has no native Python form
t5 = gh("Point", )  # component has no native Python form
t3 = line(t4, t5)
t6 = gh("Loop Start", )  # component has no native Python form
t7 = gh("Loop End", )  # component has no native Python form
t8 = end_points(None)
t9 = gh("Button", )  # component has no native Python form
t10 = gh("Random", t1, 1, 2)  # component has no native Python form
t11 = gh("Random", t2, 1, 2)  # component has no native Python form
t12 = gh("List Item", )  # component has no native Python form
t13 = gh("Integer", )  # component has no native Python form
t14 = gh("Length", None)  # component has no native Python form
t15 = (None * None)
t16 = gh("Flatten Tree", None, '{0}')  # component has no native Python form
t17 = gh("List Length", t16)  # component has no native Python form
t18 = (None * None)
t19 = gh("Partition List", t10, v2)  # component has no native Python form
t20 = gh("Partition List", t11, v2)  # component has no native Python form
t22 = unit_z(1.0)
t27 = gh("Radians", t20)  # component has no native Python form
t23 = gh("Unit X", 1.0)  # component has no native Python form
t21 = gh("Rotate 3D", t22, t27, internal("gh_point3d"), t23)  # component has no native Python form
t26 = gh("Radians", t19)  # component has no native Python form
t25 = unit_z(1.0)
t24 = gh("Rotate 3D", t21[0], t26, internal("gh_point3d"), t25)  # component has no native Python form
t28 = gh("Graft Tree", t24[0])  # component has no native Python form
t29 = gh("Line SDL", None, t28, 1.0)  # component has no native Python form
t30 = pipe(None, 1.0, 0)
t31 = gh("Integer", )  # component has no native Python form
