t2 = gh("Point", )  # component has no native Python form
v1 = 1024.302
t4 = gh("Construct Domain", 0.0, v1)  # component has no native Python form
v4 = 272.0
t3 = gh("Range", t4, v4)  # component has no native Python form
v2 = 16.231
v3 = 89.125
t7 = gh("Construct Domain", 0.0, v3)  # component has no native Python form
t6 = gh("Range", t7, v4)  # component has no native Python form
t1 = gh("Point Cylindrical", t2, t3, v2, t6)  # component has no native Python form
t5 = gh("Bifocals", None)  # component has no native Python form
t8 = gh("Group", )  # component has no native Python form
t9 = gh("Group", )  # component has no native Python form
t10 = gh("Group", )  # component has no native Python form
t11 = gh("Group", )  # component has no native Python form
t12 = gh("Group", )  # component has no native Python form
t13 = gh("Group", )  # component has no native Python form
t14 = gh("Line SDL", t2, internal("gh_point3d"), v3)  # component has no native Python form
t15 = gh("Group", )  # component has no native Python form
t18 = gh("Interpolate", t1, 3, False, 1)  # component has no native Python form
t16 = gh("Loft", t14, False)  # component has no native Python form
t17 = gh("Group", )  # component has no native Python form
t19 = gh("Group", )  # component has no native Python form
t20 = gh("Group", )  # component has no native Python form
t23 = gh("Number", )  # component has no native Python form
v5 = 65.0
t21 = gh("Divide Domain²", t16, t23, v5)  # component has no native Python form
t22 = gh("Group", )  # component has no native Python form
t24 = gh("Group", )  # component has no native Python form
t25 = divide_curve(t14, v5, False)
t26 = gh("Group", )  # component has no native Python form
t27 = gh("XY Plane", t25[0])  # component has no native Python form
t28 = gh("Group", )  # component has no native Python form
t31 = gh("Isotrim", t16, t21)  # component has no native Python form
t29 = gh("Project", t31, t27)  # component has no native Python form
t30 = gh("Group", )  # component has no native Python form
t32 = gh("Group", )  # component has no native Python form
t33 = cull_index(t29[0], v5, True)
t34 = gh("Group", )  # component has no native Python form
t35 = gh("Group", )  # component has no native Python form
t36 = gh("Surface", )  # component has no native Python form
t37 = gh("Group", )  # component has no native Python form
t40 = unit_z(1.0)
t38 = gh("Extrude", t36, t40)  # component has no native Python form
t39 = gh("Group", )  # component has no native Python form
t41 = gh("Group", )  # component has no native Python form
t42 = gh("List Item", )  # component has no native Python form
t43 = gh("Group", )  # component has no native Python form
t44 = gh("Distance", None, None)  # component has no native Python form
t45 = gh("Group", )  # component has no native Python form
v11 = 5.0
t117 = (v2 / v11)
t46 = gh("Cylinder", t2, t117, v3)  # component has no native Python form
t47 = gh("Group", )  # component has no native Python form
t128 = gh("Point Cylindrical", t2, t3, 1.0, t6)  # component has no native Python form
t129 = gh("Interpolate", t128, 3, False, 1)  # component has no native Python form
v6 = 90.0
t48 = divide_curve(t129[0], v6, False)
t49 = gh("Group", )  # component has no native Python form
t91 = unit_z(1.0)
v10 = -0.01
t93 = gh("Amplitude", t91, v10)  # component has no native Python form
t96 = gh("Move", t48[0], t93)  # component has no native Python form
t50 = gh("Cylinder", t96[0], 0.5, 1.0)  # component has no native Python form
t51 = gh("Group", )  # component has no native Python form
t52 = gh("Group", )  # component has no native Python form
t53 = gh("Group", )  # component has no native Python form
t54 = gh("Group", )  # component has no native Python form
t55 = gh("Group", )  # component has no native Python form
t56 = (v3 / v1)
t57 = gh("Group", )  # component has no native Python form
t58 = (None * None)
t59 = gh("Group", )  # component has no native Python form
t60 = gh("Group", )  # component has no native Python form
v7 = 169.0
t61 = gh("Group", )  # component has no native Python form
t62 = unit_z(1.0)
t63 = gh("Group", )  # component has no native Python form
t64 = gh("Amplitude", t62, 1.0)  # component has no native Python form
t65 = gh("Group", )  # component has no native Python form
t121 = gh("Number", )  # component has no native Python form
t123 = gh("Number", )  # component has no native Python form
t119 = gh("Extend Curve", t18[0], t121, t123, t123)  # component has no native Python form
t66 = gh("Move", t119, t64)  # component has no native Python form
t67 = gh("Group", )  # component has no native Python form
v8 = 0.8
t125 = gh("Number", )  # component has no native Python form
t68 = pipe(t66[0], v8, t125)
t69 = gh("Group", )  # component has no native Python form
t70 = (None * None)
t71 = gh("Group", )  # component has no native Python form
t72 = (None * None)
t73 = gh("Group", )  # component has no native Python form
t76 = gh("Pi", 1.0)  # component has no native Python form
t78 = gh("Number", )  # component has no native Python form
t74 = (t76 / t78)
t75 = gh("Group", )  # component has no native Python form
t77 = gh("Group", )  # component has no native Python form
t79 = gh("Group", )  # component has no native Python form
t80 = (None / v6)
t81 = gh("Group", )  # component has no native Python form
t82 = (None * None)
t83 = gh("Group", )  # component has no native Python form
t84 = gh("Number", )  # component has no native Python form
t85 = gh("Group", )  # component has no native Python form
t86 = gh("Group", )  # component has no native Python form
t87 = gh("Group", )  # component has no native Python form
t88 = gh("Group", )  # component has no native Python form
t89 = (None * None)
t90 = gh("Group", )  # component has no native Python form
v9 = 59.0
t92 = gh("Group", )  # component has no native Python form
t94 = gh("Group", )  # component has no native Python form
t95 = gh("Group", )  # component has no native Python form
t97 = gh("Group", )  # component has no native Python form
t98 = gh("Group", )  # component has no native Python form
t99 = (None - None)
t100 = gh("Group", )  # component has no native Python form
t101 = gh("Group", )  # component has no native Python form
t102 = gh("Group", )  # component has no native Python form
t103 = gh("Cap Holes", t68)  # component has no native Python form
t104 = gh("Group", )  # component has no native Python form
t111 = gh("Cap Holes", t50)  # component has no native Python form
t105 = solid_union(t103)
t106 = gh("Group", )  # component has no native Python form
t107 = gh("Group", )  # component has no native Python form
t108 = gh("Cap Holes", t46)  # component has no native Python form
t109 = gh("Group", )  # component has no native Python form
t110 = gh("Group", )  # component has no native Python form
t112 = gh("Group", )  # component has no native Python form
t113 = gh("Group", )  # component has no native Python form
t114 = gh("Group", )  # component has no native Python form
t115 = gh("Group", )  # component has no native Python form
t116 = gh("Group", )  # component has no native Python form
t118 = gh("Group", )  # component has no native Python form
t120 = gh("Group", )  # component has no native Python form
t122 = gh("Group", )  # component has no native Python form
t124 = gh("Group", )  # component has no native Python form
t126 = gh("Group", )  # component has no native Python form
t127 = gh("Group", )  # component has no native Python form
t130 = gh("Group", )  # component has no native Python form
t131 = gh("Group", )  # component has no native Python form
t132 = (None - None)
t133 = gh("Group", )  # component has no native Python form
t134 = gh("Group", )  # component has no native Python form
t135 = gh("Group", )  # component has no native Python form
t136 = gh("Group", )  # component has no native Python form
t137 = gh("Group", )  # component has no native Python form
t138 = gh("Group", )  # component has no native Python form
t139 = gh("Group", )  # component has no native Python form
t140 = gh("Group", )  # component has no native Python form
t141 = solid_union(t108)
t142 = gh("Group", )  # component has no native Python form
t143 = gh("Group", )  # component has no native Python form
t144 = gh("Group", )  # component has no native Python form
t147 = gh("Colour", )  # component has no native Python form
t145 = gh("Custom Preview", t141, t147)  # component has no native Python form
t146 = gh("Group", )  # component has no native Python form
t148 = gh("Group", )  # component has no native Python form
t149 = gh("Group", )  # component has no native Python form
t150 = gh("Colour", )  # component has no native Python form
t151 = gh("Group", )  # component has no native Python form
t152 = gh("Custom Preview", t105, t150)  # component has no native Python form
t153 = gh("Group", )  # component has no native Python form
t154 = (None - None)
t155 = gh("Group", )  # component has no native Python form
t156 = gh("Number", )  # component has no native Python form
t157 = gh("Group", )  # component has no native Python form
t158 = (None * None)
t159 = gh("Group", )  # component has no native Python form
v12 = 1.3
